# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Traveling Air Quality Recorder
subtitle: TRAQR
sponsor: Goshen College Physics
sponsorsite: https://www.goshen.edu/
email: johnrb@goshen.edu
description: > # this means to ignore newlines until "baseurl:"
  We are a research group at Goshen College investigating air quality in
  Elkhart County. We are designing an inexpensive portable datalogger that
  can be mounted on a car and collects air quality data in real time. 
baseurl: "" # just for local testing
url: ""
#baseurl: "/~stu_phys/traqr" # the subpath of your site, e.g. /blog
#url: "http://people.goshen.edu" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
#gems:
exclude:
  - Gemfile
  - Gemfile.lock
  - push_updates.sh
  - README.md
